### ISSUE TITLE
Possible to remove typescript dependency?

### ISSUE THREAD

**Issue by prasad0612** [kopach/karma-sabarivka-reporter#179]
Hi First of all thanks for this package. It does all things which I am looking for.
Only 1 problem, we have fixed the typescript version to 3.5.3 beyond which we can not move as it causes issues in our protractor integration tests. Since this package depends on typescript@3.9.5 , it is causing integration test compilation issues in application build on top of our framework.

Is it possible to remove  typescript dependency for this package?

**Comment by kopach** [comment]
Hi @prasad0612. Thank you for your feedback. TypeScript is essential and I cannot remove it. Also I'm trying to keep dependencies updated as much as possible and that's why I have newer version of typescript here. However, if there is such request – I'm fine to lower typescript dependency. This tool will work fine also with TS version 3.5.3. 
Feel free to rise PR with lower TS version - I'll merge it. Or wait a couple of days and I'll do this myself. Thank you.

**Comment by kopach** [comment]
Hi @prasad0612. Just started looking on this. Could you, please, share the exact error you get? Maybe I'll be able to help you without downgrading typescript

**Comment by prasad0612** [comment]
@kopach We have decided to hard code typescript version in the application's package.json which is fixing the issue.
Thanks for your time
